annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Portworx
  catalog.cattle.io/release-name: portworx
apiVersion: v1
appVersion: "2.8"
description: A Helm chart for installing Portworx on Kubernetes.
home: https://portworx.com/
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/k8s-porx.png
keywords:
- Storage
- ICP
- persistent disk
- pvc
- cloud native storage
- persistent storage
- portworx
- amd64
kubeVersion: '>=1.16.0'
maintainers:
- email: hadesai@purestorage.com
  name: harsh-px
- email: onaumov@purestorage.com
  name: trierra
- email: tasharma@purestorage.com
  name: sharma-tapas
- email: dahuang@purestorage.com
  name: dahuang-purestorage
name: portworx
sources:
- https://github.com/portworx/helm
version: 2.8.0
